"""Add creator_id to groups

Revision ID: c76f29868a0c
Revises: ed3411a4b126
Create Date: 2025-09-29 22:36:00.558750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76f29868a0c'
down_revision: Union[str, Sequence[str], None] = 'ed3411a4b126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'creator_id')
    # ### end Alembic commands ###
